### ISSUE TITLE
Figure out why rc versions are installed

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II/profile-collection-ci#7]
The tests in https://github.com/NSLS-II-SMI/profile_collection/pull/10 failed due to the `rc` version of ophyd (v1.4.0rc2) was installed.  The build is here: https://dev.azure.com/nsls2/profile_collections/_build/results?buildId=108.

**Comment by tacaswell** [comment]
Conda does not respect pre-release version parsing like `pip` does.  We should make sure that the rc builds end up in a different tag.
